apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Tracing
    type: jaeger
    access: proxy
    url: http://tracing:16686
